# Generated by Django 5.2.17 on 2026-08-24 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('obligaciones', '0002_obligacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionRecordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('dias_antes', models.PositiveSmallIntegerField(help_text='0 significa el mismo día del vencimiento.', verbose_name='Días antes')),
                ('canal', models.CharField(choices=[('APP', 'Notificación en la aplicación'), ('EMAIL', 'Correo electrónico')], default='APP', max_length=10, verbose_name='Canal')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('obligacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_recordatorio', to='obligaciones.obligacion', verbose_name='Obligación')),
            ],
            options={
                'verbose_name': 'Regla de recordatorio',
                'verbose_name_plural': 'Reglas de recordatorio',
                'ordering': ['-dias_antes'],
            },
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('dias_antes', models.PositiveSmallIntegerField(verbose_name='Días antes')),
                ('fecha_programada', models.DateField(verbose_name='Fecha programada')),
                ('canal', models.CharField(choices=[('APP', 'Notificación en la aplicación'), ('EMAIL', 'Correo electrónico')], default='APP', max_length=10, verbose_name='Canal')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('CANCELADO', 'Cancelado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=10, verbose_name='Estado')),
                ('fecha_envio', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío')),
                ('detalle_error', models.TextField(blank=True, verbose_name='Detalle del error')),
                ('obligacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='obligaciones.obligacion', verbose_name='Obligación')),
                ('regla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recordatorios', to='recordatorios.configuracionrecordatorio', verbose_name='Regla que lo originó')),
            ],
            options={
                'verbose_name': 'Recordatorio',
                'verbose_name_plural': 'Recordatorios',
                'ordering': ['fecha_programada'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('mensaje', models.TextField(verbose_name='Mensaje')),
                ('url_destino', models.CharField(blank=True, max_length=255, verbose_name='Enlace')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de lectura')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('recordatorio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='recordatorios.recordatorio', verbose_name='Recordatorio')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.AddConstraint(
            model_name='configuracionrecordatorio',
            constraint=models.UniqueConstraint(fields=('obligacion', 'dias_antes', 'canal'), name='uq_regla_recordatorio'),
        ),
        migrations.AddIndex(
            model_name='recordatorio',
            index=models.Index(fields=['estado', 'fecha_programada'], name='recordatori_estado_080e83_idx'),
        ),
        migrations.AddConstraint(
            model_name='recordatorio',
            constraint=models.UniqueConstraint(fields=('obligacion', 'dias_antes', 'fecha_programada', 'canal'), name='uq_recordatorio_idempotente'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['usuario', 'leida'], name='recordatori_usuario_1a5879_idx'),
        ),
    ]
