# Generated by Django 5.2.17 on 2026-08-24 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('nombre', models.CharField(max_length=80, verbose_name='Nombre')),
                ('codigo', models.SlugField(blank=True, help_text='Identificador estable de las categorías predeterminadas. Vacío en las creadas por un usuario.', max_length=60, null=True, unique=True, verbose_name='Código')),
                ('ambito', models.CharField(choices=[('PERSONAL', 'Solo personal'), ('EMPRESA', 'Solo empresa'), ('AMBOS', 'Personal y empresa')], default='AMBOS', max_length=10, verbose_name='Ámbito')),
                ('color', models.CharField(default='#6B7280', max_length=7, verbose_name='Color')),
                ('icono', models.CharField(blank=True, max_length=40, verbose_name='Icono')),
                ('peso_prioridad', models.PositiveSmallIntegerField(default=0, help_text='De 0 a 5. Aporta al puntaje de prioridad de las obligaciones (§12).', verbose_name='Peso en el cálculo de prioridad')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('usuario', models.ForeignKey(blank=True, help_text='Vacío significa que es una categoría predeterminada del sistema.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to=settings.AUTH_USER_MODEL, verbose_name='Usuario propietario')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
                'constraints': [models.UniqueConstraint(fields=('usuario', 'nombre'), name='uq_categoria_usuario_nombre')],
            },
        ),
    ]
