# Generated by Django 5.2.17 on 2026-08-24 20:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obligaciones', '0001_initial'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Obligacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('concepto', models.CharField(max_length=150, verbose_name='Concepto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Valor')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de vencimiento')),
                ('enlace_pago', models.URLField(blank=True, max_length=500, verbose_name='Enlace de pago')),
                ('prioridad_usuario', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=6, verbose_name='Prioridad')),
                ('pagada', models.BooleanField(default=False, verbose_name='Pagada')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('proveedor', models.CharField(blank=True, max_length=150, verbose_name='Proveedor')),
                ('referencia', models.CharField(blank=True, max_length=80, verbose_name='Referencia o número de factura')),
                ('eliminada_en', models.DateTimeField(blank=True, null=True, verbose_name='Eliminada en')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='obligaciones', to='obligaciones.categoria', verbose_name='Categoría')),
                ('empresa', models.ForeignKey(blank=True, help_text='Se rellena automáticamente en las cuentas de empresa.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='obligaciones', to='usuarios.empresa', verbose_name='Empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='obligaciones', to=settings.AUTH_USER_MODEL, verbose_name='Registrada por')),
            ],
            options={
                'verbose_name': 'Obligación',
                'verbose_name_plural': 'Obligaciones',
                'ordering': ['fecha_vencimiento', '-monto'],
                'indexes': [models.Index(fields=['usuario', 'fecha_vencimiento'], name='obligacione_usuario_22470f_idx'), models.Index(fields=['empresa', 'fecha_vencimiento'], name='obligacione_empresa_503205_idx'), models.Index(fields=['pagada', 'fecha_vencimiento'], name='obligacione_pagada_fcbd65_idx')],
            },
        ),
    ]
