# Generated by Django 5.2.17 on 2026-09-21 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obligaciones', '0002_obligacion'),
        ('usuarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='obligacion',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Solo aplica a obligaciones mensuales. Vacío significa que se sigue repitiendo sin fecha de fin.', null=True, verbose_name='Repetir hasta'),
        ),
        migrations.AddField(
            model_name='obligacion',
            name='frecuencia',
            field=models.CharField(choices=[('UNICA', 'Pago único'), ('MENSUAL', 'Mensual')], default='UNICA', max_length=7, verbose_name='Frecuencia de pago'),
        ),
        migrations.AddField(
            model_name='obligacion',
            name='obligacion_recurrente',
            field=models.ForeignKey(blank=True, help_text='Vacío si es un pago único o si esta es la primera obligación de una serie mensual. Las siguientes obligaciones de la serie apuntan aquí a la primera.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='obligaciones.obligacion', verbose_name='Obligación recurrente de origen'),
        ),
        migrations.AddConstraint(
            model_name='obligacion',
            constraint=models.UniqueConstraint(fields=('obligacion_recurrente', 'fecha_vencimiento'), name='uq_periodo_recurrente'),
        ),
    ]
