# Generated by Django 5.2.17 on 2026-08-24 20:25

import apps.usuarios.managers
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre o razón social')),
                ('nit', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='NIT')),
                ('telefono', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('tipo_usuario', models.CharField(choices=[('PERSONAL', 'Personal'), ('EMPRESA', 'Empresa')], default='PERSONAL', max_length=10, verbose_name='Tipo de usuario')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Acceso al panel de administración')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='usuarios.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['nombre'],
            },
            managers=[
                ('objects', apps.usuarios.managers.UsuarioManager()),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracionUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('dias_proximo_vencimiento', models.PositiveSmallIntegerField(default=7, help_text="Una obligación pasa a 'Próxima a vencer' cuando faltan estos días o menos.", verbose_name='Días para considerar una obligación próxima a vencer')),
                ('dias_recordatorio_default', models.JSONField(blank=True, default=list, help_text='Días antes del vencimiento que se proponen al crear una obligación.', verbose_name='Recordatorios por defecto (días antes)')),
                ('notificaciones_app', models.BooleanField(default=True, verbose_name='Notificaciones en la aplicación')),
                ('notificaciones_email', models.BooleanField(default=False, verbose_name='Notificaciones por correo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración de usuario',
                'verbose_name_plural': 'Configuraciones de usuario',
            },
        ),
    ]
